services:
  db:
    image: postgres:latest
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
  web:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}_web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    working_dir: /app
    depends_on:
      - db
